In [1]:
import os
import pandas as pd
import numpy as np


In [23]:
data_path= "C:/Users/xiang/Desktop/"
DensNet_csv=f'{data_path}/stage_2_sample_submission_densnet.csv'
ResNet_csv=f'{data_path}/stage_2_sample_Resnet2.csv'
Dpn_csv=f'{data_path}/stage_2_sample_DPN3.csv'

In [9]:
densnet_df=pd.read_csv(DensNet_csv)
densnet_df.head()

NameError: name 'DensNet_csv' is not defined

In [10]:
resnet_df=pd.read_csv(ResNet_csv)
resnet_df.head()

ID     Label
0               ID_000000e27_any  0.709204
1          ID_000000e27_epidural  0.104036
2  ID_000000e27_intraparenchymal  0.067867
3  ID_000000e27_intraventricular  0.008120
4      ID_000000e27_subarachnoid  0.250185

In [11]:
dpn_df=pd.read_csv(Dpn_csv)
dpn_df.head()

ID     Label
0               ID_000000e27_any  0.205432
1          ID_000000e27_epidural  0.009480
2  ID_000000e27_intraparenchymal  0.009074
3  ID_000000e27_intraventricular  0.000196
4      ID_000000e27_subarachnoid  0.032478

In [12]:
# densnet_acc=1.-0.16741
resnet_acc=1.-0.21082
dpn_acc=1-0.16741
sum=resnet_acc+dpn_acc
sum

1.62177

In [13]:
resnet_weight=resnet_acc/sum


In [14]:
dpn_weight=dpn_acc/sum

In [16]:
resnet_value=resnet_df['Label'].values
resnet_value

array([0.70920354, 0.10403559, 0.06786692, ..., 0.00408572, 0.11234051,
       0.15871185])

In [17]:
dpn_value=dpn_df['Label'].values
dpn_value

array([0.20543152, 0.00948024, 0.00907397, ..., 0.00265709, 0.14383271,
       0.25795913])

In [19]:
merge_value=np.vstack((resnet_value,dpn_value))
merge_value

array([[0.70920354, 0.10403559, 0.06786692, ..., 0.00408572, 0.11234051,
        0.15871185],
       [0.20543152, 0.00948024, 0.00907397, ..., 0.00265709, 0.14383271,
        0.25795913]])

In [20]:
merge_result=np.average(merge_value, axis=0, weights=[resnet_weight,dpn_weight])
merge_result

array([0.45057528, 0.05549243, 0.03768359, ..., 0.00335228, 0.12850809,
       0.20966377])

In [24]:
densnet_df=pd.read_csv(DensNet_csv)
densnet_df['Label']

0         0.776680
1         0.026066
2         0.133951
3         0.031580
4         0.120550
            ...   
727387    0.019873
727388    0.061920
727389    0.005681
727390    0.094938
727391    0.443809
Name: Label, Length: 727392, dtype: float64

In [25]:
np.shape(merge_result)
densnet_df.head()

ID     Label
0               ID_000000e27_any  0.776680
1          ID_000000e27_epidural  0.026066
2  ID_000000e27_intraparenchymal  0.133951
3  ID_000000e27_intraventricular  0.031580
4      ID_000000e27_subarachnoid  0.120550

In [26]:

from pandas import Series
densnet_df['Label']=Series(merge_result)

In [27]:
densnet_df.head(20)

ID         Label
0                ID_000000e27_any  4.505753e-01
1           ID_000000e27_epidural  5.549243e-02
2   ID_000000e27_intraparenchymal  3.768359e-02
3   ID_000000e27_intraventricular  4.052051e-03
4       ID_000000e27_subarachnoid  1.384175e-01
5           ID_000000e27_subdural  2.503918e-01
6                ID_000009146_any  1.013235e-03
7           ID_000009146_epidural  4.824212e-07
8   ID_000009146_intraparenchymal  1.068606e-05
9   ID_000009146_intraventricular  6.467328e-07
10      ID_000009146_subarachnoid  4.173368e-04
11          ID_000009146_subdural  2.736665e-04
12               ID_00007b8cb_any  6.830614e-02
13          ID_00007b8cb_epidural  1.927903e-03
14  ID_00007b8cb_intraparenchymal  9.833680e-03
15  ID_00007b8cb_intraventricular  6.172852e-03
16      ID_00007b8cb_subarachnoid  4.147893e-02
17          ID_00007b8cb_subdural  1.796419e-02
18               ID_000134952_any  5.826243e-02
19          ID_000134952_epidural  5.040108e-03

In [28]:
densnet_df.to_csv('stage_2_sample_submission_merge2.csv', index=False)
